version: '3'

services:
  proxy:
    container_name: proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile

    ports:
      - 80:80

    networks:
      - fcnet  

    depends_on:
      - app

  app:
    image: node:20
    container_name: app
    
    command: sh -c "cd /app && npm install && chmod +x ./wait-for-it.sh && ./wait-for-it.sh db:3306 -t 40 -- node index.js"

    networks:
      - fcnet

    volumes:
      - "./node:/app"

  db:
    container_name: db   
    
    build:
      context: ./mysql
      dockerfile: Dockerfile

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
      
    command: --innodb-use-native-aio=0
    restart: always

    networks:
      - fcnet

    expose:
      - 3306      

networks:
  fcnet:
    driver: bridge  